modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/Cheesecuter/SculkAndJaw/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://modrinth.com/mod/sculkandjaw"
logoFile="assets/ycpk/icon.png"
credits='''
Cheesecuter, WuYuZeGang
Thanks to The1Yang1, yoyolyq, JoanDaro for testing and suggestions and also to sculklatch mod with HerrChaos, RedVortexDev, TheTrueYak and unroman for providing inspiration for this mod.
'''
authors = "${mod_authors}"
displayTest="MATCH_VERSION"
description = '''${mod_description}'''
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
