modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Cheesecuter/SculkJaw/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/sculkandjaw"
logoFile="assets/ycpk/icon.png"
credits="The1Yang1, yoyolyq, JoanDaro"
authors="Cheesecuter, WuYuZeGang"
description='''
This mod expanded sculk blocks family and add few new effects, Ancient City and Deep Dark is more dangerous now.
'''

[[mixins]]
config="sculkandjaw.mixins.json"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
